[theme]
primaryColor = "#4f46e5"
backgroundColor = "#f5f9ff"
secondaryBackgroundColor = "#ffffff"
textColor = "#0f172a"
font = "sans serif"

[client]
toolbarMode = "minimal"
showErrorDetails = "none"

[server]
runOnSave = true
headless = true

[browser]
gatherUsageStats = false
